# Generated by Django 4.1.4 on 2023-09-25 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='approved',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
