# Generated by Django 4.1.4 on 2023-09-29 23:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_person_approved'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100)),
                ('date_created', models.DateTimeField(verbose_name='date published')),
                ('date_lab', models.DateTimeField()),
                ('comment', models.CharField(max_length=1000)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.person')),
            ],
        ),
    ]
