# Generated by Django 4.1.4 on 2023-10-01 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_formquestion_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='formquestion',
            name='tooltip',
            field=models.CharField(default=0, max_length=1000),
            preserve_default=False,
        ),
    ]
