# Generated by Django 4.1.4 on 2023-10-01 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_formquestion_tooltip'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='is_completed',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
