# Generated by Django 4.1.4 on 2023-10-01 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_form_is_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='is_main',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
