# Generated by Django 4.1.4 on 2023-10-01 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0008_form_is_main'),
    ]

    operations = [
        migrations.AddField(
            model_name='formquestion',
            name='is_necessary',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
