# Generated by Django 4.1.4 on 2023-10-01 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0009_formquestion_is_necessary'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentchoice',
            name='text',
            field=models.CharField(default=0, max_length=2000),
            preserve_default=False,
        ),
    ]
